### ISSUE TITLE
can we make librato load apikey and username from App Settings section of web.config 

### ISSUE THREAD

**Issue by Ashishks1987** [plmwong/librato4net#3]
I am hosting my web app on AWS, so pushing the librato username and api key from Elastic Beanstalk but the problem is that EBS would push them to the App Settings section of the web.config file. Is there any possibility that I can load them from there?

**Comment by plmwong** [comment]
Sure. I'll add the option of supplying configuration through the regular `appSettings`, mostly likely through convention based key names.

**Comment by Ashishks1987** [comment]
Thanks a lot for the quick response. When can we expect the fix/improvement to be rolled out?

**Comment by plmwong** [comment]
I've pushed up a new version to NuGet.org: https://www.nuget.org/packages/librato4net/1.2.0.1651

You'll have to use `MetricsPublisher.Start(settingsSource: SettingsSource.AppSettings)`, or pass in an `AppSettingsLibratoSettings` instance to the `LibratoClient` if you're instantiating manually.

The `appSettings` keys are `Librato.Username`, `Librato.ApiKey`, `Librato.ApiEndPoint` and `Librato.SendInterval`.

**Comment by Ashishks1987** [comment]
That would help me save lots of efforts. Thanks a lot Phillip.
